version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17-trixie
    container_name: design-buddy-postgres
    environment:
      POSTGRES_DB: design-buddy_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
